### PR TITLE
grunt-jekyll: run jekyll with `bundle exec`

### PR DESCRIPTION
**Pull request by mightyiam**

### CODE REVIEW

**Comment by mightyiam** [comment]
https://github.com/dannygarcia/grunt-jekyll#bundleexec

**Comment by mightyiam** [comment]
This way we run the Jekyll version that is installed via Bundler (the Gemfile).

**Comment by mightyiam** [comment]
I desire to carry on. Small change. Please post–review.

**Comment by winhamwr** [comment]
Nice!

**Comment by mightyiam** [comment]
Thank you.

**Pull request merged**
