### PR TITLE
Register class toggling (style)

### PR DESCRIPTION
**Pull request by mightyiam**

### CODE REVIEW

**Comment by mightyiam** [comment]
Fixes #684

**Comment by mightyiam** [comment]
Please review.

**Comment by winhamwr** [comment]
Shouldn't this come with a CHANGELOG entry for RC.3?

Good to merge, other than that.

**Comment by mightyiam** [comment]
> Shouldn't this come with a CHANGELOG entry for RC.3?

Indeed. Here it is. I guess I was proud of how easy this was.

**Pull request merged**
